server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri:
                http://localhost:8081
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri:
                http://localhost:8082
              predicates:
                - Path=/api/orders/**


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway